### ISSUE TITLE
MultiMapDataStore

### ISSUE THREAD

**Issue by 2ndGAB** [Arman92/Mapsforge-OsmDroid-GraphHopper#1]
Hi Arman92,
Will you update your package with mapsforge 0.6.0 and use MultiMapDatastore?

Regards,
Al

**Comment by Arman92** [comment]
Hi,

I updated mapsforge to 0.6.0 and added graphhopper for offline routing.

**Comment by 2ndGAB** [comment]
Cool, I'll give it a try.

**Comment by Arman92** [comment]
For graphhopper, you need appropriate routing files, I didn't have time to explain how to obtain (or make) them, but you can read the Wikis of graphhopper GitHub page.
